// @ts-nocheck
export const SKILL_CATALOG = [
  { id: 'code-review', name: 'Code Review', category: 'Development',
    description: 'Rigorous review discipline for any code you produce or inspect',
    instructions: 'After writing or modifying code, review it before declaring done: check error handling on every failure path, verify edge cases (empty, null, boundary), and confirm names describe intent. When asked to review code, report findings ordered by severity with file:line references and a concrete fix for each.' },
  { id: 'tdd', name: 'Test-Driven', category: 'Development',
    description: 'Write the failing test before the implementation',
    instructions: 'For every feature or bugfix: write a failing test first, run it to confirm it fails for the expected reason, implement the minimal change to pass, then run the full suite. Never claim work is done without showing test output.' },
  { id: 'debugging', name: 'Systematic Debugging', category: 'Development',
    description: 'Root-cause before fixing',
    instructions: 'When something fails, reproduce it first, read the full error output, and trace the failing value to its origin before proposing any fix. State the root cause explicitly before changing code. Never stack a second fix on an unverified first one.' },
  { id: 'refactor', name: 'Refactoring', category: 'Development',
    description: 'Small, behavior-preserving steps',
    instructions: 'Refactor in small, independently verifiable steps that preserve behavior. Run tests between steps. Never mix refactoring with feature changes in one edit. Preserve public interfaces unless explicitly asked to change them.' },
  { id: 'git-flow', name: 'Git Discipline', category: 'Development',
    description: 'Clean commits, branch hygiene',
    instructions: 'Make small, focused commits with imperative-mood messages describing why, not just what. Check git status and diff before committing. Never commit secrets, build artifacts, or unrelated changes. Work on feature branches, not main, unless told otherwise.' },
  { id: 'docs', name: 'Documentation', category: 'Writing',
    description: 'Document alongside changes',
    instructions: 'When adding or changing functionality, update affected documentation (README, comments explaining non-obvious constraints) in the same change. Write for a reader who has not seen this conversation. Prefer examples over abstract description.' },
  { id: 'planning', name: 'Plan First', category: 'Process',
    description: 'Outline before executing multi-step work',
    instructions: 'For any task needing more than two steps, present a short numbered plan before executing, then follow it, noting deviations. Surface risks and assumptions in the plan rather than discovering them mid-task.' },
  { id: 'concise', name: 'Concise Output', category: 'Process',
    description: 'Terse, high-signal responses',
    instructions: 'Keep responses short: lead with the outcome, cut preamble and restatement, use lists over prose where structure helps. Show only the code that changed, not whole files, unless asked.' },
];
